// Rules.jsx (Generated by ChatGPT)
import React, { useEffect, useRef, useState } from "react";
import "../styles/Rules.css";
import psyduck from "../assets/img/psyduck_huh.png";

const ENTER_DURATION = 400;
const EXIT_DURATION = 350;

export default function Rules({ isVisible, onClickButton }) {
  const onClose = onClickButton || (() => {});
  const [state, setState] = useState("hidden");
  const rootRef = useRef(null);
  const timeoutRef = useRef(null);

  useEffect(() => {
    clearTimeout(timeoutRef.current);
    if (isVisible) {
      if (state === "hidden" || state === "exiting") {
        setState("entering");
        timeoutRef.current = setTimeout(
          () => setState("entered"),
          ENTER_DURATION
        );
      }
    } else {
      if (state === "entering" || state === "entered") {
        setState("exiting");
        timeoutRef.current = setTimeout(
          () => setState("hidden"),
          EXIT_DURATION
        );
      }
    }
    return () => clearTimeout(timeoutRef.current);
  }, [isVisible, state]);

  useEffect(() => {
    const handleOutside = (e) => {
      if (
        (state === "entering" || state === "entered") &&
        rootRef.current &&
        !rootRef.current.contains(e.target)
      ) {
        onClose();
      }
    };
    const handleKey = (e) => {
      if ((state === "entering" || state === "entered") && e.key === "Escape")
        onClose();
    };
    document.addEventListener("mousedown", handleOutside);
    document.addEventListener("keydown", handleKey);
    return () => {
      document.removeEventListener("mousedown", handleOutside);
      document.removeEventListener("keydown", handleKey);
    };
  }, [state, onClose]);

  if (state === "hidden") return null;

  const rootClass = `game-rules-root ${state}`;
  const boxClass = `rules-box ${state}`;
  const psyClass = `psyduck ${state}`;

  return (
    <div
      ref={rootRef}
      className={rootClass}
      onClick={(e) => e.stopPropagation()}
    >
      <div className={boxClass}>
        <ul>
          <li>Don't click the same card twice!</li>
          <li>Click on the logo to go back.</li>
          <li>Tip : Turn on music :D </li>
        </ul>
        <p></p>
        <p></p>
        <p></p>
      </div>
      <div className={psyClass}>
        <img src={psyduck} alt="Psyduck" className="psy-img" />
      </div>
    </div>
  );
}
